// Static manifest of every file under /public/icons.
// Generated by: `ls public/icons > ...` — regenerate if icons change.
// Kept as a Set so we can pick the first matching URL candidate without
// firing a broken-image request.
export const ICON_MANIFEST: ReadonlySet<string> = new Set([
  "Detonator.png",
  "GasMask.png",
  "HardDrive.png",
  "IconDesc_AIExpension.png",
  "IconDesc_AILimiter.png",
  "IconDesc_AlienDNA.png",
  "IconDesc_AlienPowerMatrix.png",
  "IconDesc_AlienProtein.png",
  "IconDesc_AluminiumCasing.png",
  "IconDesc_AluminiumIngot.png",
  "IconDesc_AluminiumScrap.png",
  "IconDesc_AluminiumSheet.png",
  "IconDesc_AssemblyDirectorSystem.png",
  "IconDesc_BallisticWarpDrive.png",
  "IconDesc_Battery.png",
  "IconDesc_Bauxite.png",
  "IconDesc_Beacon.png",
  "IconDesc_Berry.png",
  "IconDesc_BiochemicalSculptor.png",
  "IconDesc_Biomass_Final.png",
  "IconDesc_Cables.png",
  "IconDesc_CaneEquipment.png",
  "IconDesc_CateriumIngot.png",
  "IconDesc_CateriumOre.png",
  "IconDesc_CircuitBoard.png",
  "IconDesc_Cluster.png",
  "IconDesc_CoalOre.png",
  "IconDesc_ColorCartridge.png",
  "IconDesc_ColorGun.png",
  "IconDesc_CompactedCoal.png",
  "IconDesc_Computer.png",
  "IconDesc_Concrete.png",
  "IconDesc_ConversionCube.png",
  "IconDesc_CoolingSystem.png",
  "IconDesc_CopperDust.png",
  "IconDesc_CopperIngot.png",
  "IconDesc_CopperSheet.png",
  "IconDesc_CrystalOscillator.png",
  "IconDesc_DarkEnergy.png",
  "IconDesc_Diamonds.png",
  "IconDesc_DissolvedSilica.png",
  "IconDesc_ElectromagneticControlRod.png",
  "IconDesc_EmptyCannister.png",
  "IconDesc_EncasedPlutoniumCell.png",
  "IconDesc_EncasedSteelBeam.png",
  "IconDesc_Engine.png",
  "IconDesc_ExoticMatter.png",
  "IconDesc_Explosive.png",
  "IconDesc_Fabric.png",
  "IconDesc_Ficsit_Coupon.png",
  "IconDesc_FicsiteIngot.png",
  "IconDesc_FicsiteMesh.png",
  "IconDesc_FicsoniumCell.png",
  "IconDesc_FicsoniumFuelRod.png",
  "IconDesc_Fuel.png",
  "IconDesc_FusedModularFrame.png",
  "IconDesc_Gas.png",
  "IconDesc_GasMaskFilter.png",
  "IconDesc_Gunpowder.png",
  "IconDesc_GunpowderMk2.png",
  "IconDesc_HatcherPart.png",
  "IconDesc_HazmatFilter.png",
  "IconDesc_HazmatSuit.png",
  "IconDesc_Heatsink.png",
  "IconDesc_HighSpeedConnector.png",
  "IconDesc_HogPart.png",
  "IconDesc_HubParts.png",
  "IconDesc_IonizedFuel.png",
  "IconDesc_IonizedRocketFuel.png",
  "IconDesc_IronIngot.png",
  "IconDesc_IronPlates.png",
  "IconDesc_IronRods.png",
  "IconDesc_IronScrews.png",
  "IconDesc_Leaves.png",
  "IconDesc_LiquidBiofuel.png",
  "IconDesc_LiquidBiofuel_Pipe.png",
  "IconDesc_LiquidFuel_Pipe.png",
  "IconDesc_LiquidHeavyOilResidue_Pipe.png",
  "IconDesc_LiquidSulfuricAcid_Pipe.png",
  "IconDesc_LiquidTurboFuel_Pipe.png",
  "IconDesc_MagneticFieldGenerator.png",
  "IconDesc_ModularFrame.png",
  "IconDesc_ModularFrameHeavy.png",
  "IconDesc_Mycelia.png",
  "IconDesc_NitricAcid.png",
  "IconDesc_NitrogenGas.png",
  "IconDesc_NonFissileUranium.png",
  "IconDesc_NuclearCell.png",
  "IconDesc_NuclearFuelRod.png",
  "IconDesc_NuclearPasta.png",
  "IconDesc_NuclearWaste.png",
  "IconDesc_Nuke.png",
  "IconDesc_PackagedAluminaSolution.png",
  "IconDesc_PackagedNitricAcid.png",
  "IconDesc_PackagedNitrogen.png",
  "IconDesc_PackagedRocketFuel.png",
  "IconDesc_PackagedWater.png",
  "IconDesc_PckagedSulphuricAcid.png",
  "IconDesc_PetroleumCoke.png",
  "IconDesc_Plastic.png",
  "IconDesc_PlutoniumFuelRod.png",
  "IconDesc_PlutoniumPellet.png",
  "IconDesc_PlutoniumWaste.png",
  "IconDesc_PolymerResin.png",
  "IconDesc_PressureTank.png",
  "IconDesc_QuantumComputer.png",
  "IconDesc_QuantumCrystal.png",
  "IconDesc_QuantumEnergy.png",
  "IconDesc_QuartzCrystal.png",
  "IconDesc_QuartzResource.png",
  "IconDesc_Quickwire.png",
  "IconDesc_RadioControlUnit.png",
  "IconDesc_ReanimatedSam.png",
  "IconDesc_RebarGun.png",
  "IconDesc_ReinforcedIronPlates.png",
  "IconDesc_RocketFuelPipe.png",
  "IconDesc_Rotor.png",
  "IconDesc_Rubber.png",
  "IconDesc_SamFluctuator.png",
  "IconDesc_SameOre.png",
  "IconDesc_Shock.png",
  "IconDesc_Silica.png",
  "IconDesc_SingularityCell.png",
  "IconDesc_SolidBiofuel.png",
  "IconDesc_SpelevatorPart_1.png",
  "IconDesc_SpelevatorPart_2.png",
  "IconDesc_SpelevatorPart_4.png",
  "IconDesc_SpelevatorPart_5.png",
  "IconDesc_SpikedRebar.png",
  "IconDesc_SpitterPart.png",
  "IconDesc_Stator.png",
  "IconDesc_SteelBeam.png",
  "IconDesc_SteelIngot.png",
  "IconDesc_SteelPipe.png",
  "IconDesc_StingerPart.png",
  "IconDesc_SuperPositionOscillator.png",
  "IconDesc_TemporalProcessor.png",
  "IconDesc_ThermalPropulsionRocket.png",
  "IconDesc_TimeCrystal.png",
  "IconDesc_TurboFuel.png",
  "IconDesc_TurboMotor.png",
  "IconDesc_UraniumOre.png",
  "IconDesc_UraniumPellets.png",
  "IconDesc_Vines.png",
  "IconDesc_Wire.png",
  "IconDesc_Wood.png",
  "IconDesc_XenoBasher.png",
  "IconDesc_XenoZapper.png",
  "IconDesc_copper_new.png",
  "IconDesc_iron_new.png",
  "Inhaler.png",
  "Jetpack.png",
  "LiquidAlumina_Pipe.png",
  "LiquidOil_Pipe.png",
  "LiquidWater_Pipe.png",
  "Mushroom.png",
  "ObjectScanner.png",
  "Oil.png",
  "OilResidue.png",
  "Parachute.png",
  "PowerShard.png",
  "PowerSlugGreen.png",
  "PowerSlugPurple.png",
  "PowerSlugYellow.png",
  "RifleMk1.png",
  "Rifle_Magazine.png",
  "SpelevatorPart_3.png",
  "Stone.png",
  "Sulfur.png"
]);

/**
 * Explicit overrides for products whose game-data class name doesn't match
 * any of our pattern-derived candidates. Keep this small — patterns should
 * catch most cases.
 */
const OVERRIDES: Record<string, string> = {
  // Icon files named after display names / with typos, where neither the
  // class name nor the display name derives the filename.
  Desc_SteelPlateReinforced_C: "IconDesc_EncasedSteelBeam.png", // "Encased Industrial Beam"
  Desc_FluidCanister_C: "IconDesc_EmptyCannister.png", // file typo: Cannister
  Desc_SpaceElevatorPart_1_C: "IconDesc_SpelevatorPart_1.png", // Smart Plating
  Desc_SpaceElevatorPart_2_C: "IconDesc_SpelevatorPart_2.png", // Versatile Framework
  Desc_SpaceElevatorPart_3_C: "SpelevatorPart_3.png", // Automated Wiring (no prefix)
  Desc_SpaceElevatorPart_4_C: "IconDesc_SpelevatorPart_4.png", // Modular Engine
  Desc_SpaceElevatorPart_5_C: "IconDesc_SpelevatorPart_5.png", // Adaptive Control Unit
  Desc_SpaceElevatorPart_12_C: "IconDesc_AIExpension.png", // AI Expansion Server (file typo)
  Desc_Motor_C: "IconDesc_Engine.png",
  Desc_GasTank_C: "IconDesc_Gas.png", // Empty Fluid Tank
  Desc_RocketFuel_C: "IconDesc_RocketFuelPipe.png",
  Desc_PackagedOilResidue_C: "OilResidue.png",
  Desc_Filter_C: "IconDesc_GasMaskFilter.png", // Gas Filter
  Desc_AlienDNACapsule_C: "IconDesc_AlienDNA.png",
  Desc_RawQuartz_C: "IconDesc_QuartzResource.png",
  Desc_OreIron_C: "IconDesc_iron_new.png",
  Desc_OreCopper_C: "IconDesc_copper_new.png",
  Desc_Water_C: "LiquidWater_Pipe.png",
  Desc_LiquidOil_C: "LiquidOil_Pipe.png",
  Desc_Coal_C: "IconDesc_CoalOre.png",
  Desc_Stone_C: "Stone.png",
  Desc_Sulfur_C: "Sulfur.png",
  Desc_OreBauxite_C: "IconDesc_Bauxite.png",
  Desc_OreGold_C: "IconDesc_CateriumOre.png",
  Desc_OreUranium_C: "IconDesc_UraniumOre.png",
  Desc_NitrogenGas_C: "IconDesc_NitrogenGas.png",
  Desc_SAM_C: "IconDesc_SameOre.png",
  Desc_IronPlate_C: "IconDesc_IronPlates.png",
  Desc_IronPlateReinforced_C: "IconDesc_ReinforcedIronPlates.png",
  Desc_IronRod_C: "IconDesc_IronRods.png",
  Desc_IronScrew_C: "IconDesc_IronScrews.png",
  Desc_Cable_C: "IconDesc_Cables.png",
  Desc_ModularFrameHeavy_C: "IconDesc_ModularFrameHeavy.png",
  Desc_LiquidFuel_C: "IconDesc_LiquidFuel_Pipe.png",
  Desc_HeavyOilResidue_C: "IconDesc_LiquidHeavyOilResidue_Pipe.png",
  Desc_LiquidTurboFuel_C: "IconDesc_LiquidTurboFuel_Pipe.png",
  Desc_SulfuricAcid_C: "IconDesc_LiquidSulfuricAcid_Pipe.png",
  Desc_AluminaSolution_C: "LiquidAlumina_Pipe.png",
  Desc_AluminumIngot_C: "IconDesc_AluminiumIngot.png",
  Desc_AluminumCasing_C: "IconDesc_AluminiumCasing.png",
  Desc_AluminumScrap_C: "IconDesc_AluminiumScrap.png",
  Desc_AluminumPlate_C: "IconDesc_AluminiumSheet.png",
  Desc_NuclearFuelRod_C: "IconDesc_NuclearFuelRod.png",
  Desc_Diamond_C: "IconDesc_Diamonds.png",
  Desc_UraniumCell_C: "IconDesc_NuclearCell.png",
  Desc_ComputerSuper_C: "IconDesc_QuantumComputer.png",
  Desc_SkeletalFrame_C: "IconDesc_HubParts.png",
  Desc_GunPowder_C: "IconDesc_Gunpowder.png"
};

const stripDesc = (product: string) => product.replace(/^Desc_/, "").replace(/_C$/, "");

// Inlined at build time. Empty in dev and the server build; the repo subpath
// when deployed to GitHub Pages. Plain <img src> doesn't get Next's automatic
// basePath handling, so we prefix here.
const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

const iconUrl = (file: string) => `${BASE_PATH}/icons/${file}`;

// Icon filenames don't follow one casing convention (SamFluctuator vs
// SAMFluctuator, Heatsink vs HeatSink) — and GitHub Pages is case-SENSITIVE
// even though macOS dev machines aren't. Look up case-insensitively but
// always return the exact on-disk filename.
const MANIFEST_BY_LOWER = new Map<string, string>();
for (const file of ICON_MANIFEST) MANIFEST_BY_LOWER.set(file.toLowerCase(), file);

const findFile = (candidate: string): string | null => MANIFEST_BY_LOWER.get(candidate.toLowerCase()) ?? null;

/**
 * Resolve a product to the best available icon URL.
 *
 * Order: override table, then naming patterns derived from the class name AND
 * the display name (many icons are named after what the item is *called*, not
 * its internal class — e.g. Desc_SteelPlate_C is displayed "Steel Beam" and
 * its icon is IconDesc_SteelBeam.png). Returns null when nothing matches so
 * the caller renders a fallback avatar.
 */
export function resolveIconUrl(product: string, displayName?: string): string | null {
  if (OVERRIDES[product]) return iconUrl(OVERRIDES[product]);

  const base = stripDesc(product);
  const stripLiquid = base.replace(/^Liquid/, "");
  // "Steel Beam" → "SteelBeam", "Non-Fissile Uranium" → "NonFissileUranium"
  const display = (displayName ?? "").replace(/[^a-zA-Z0-9]/g, "");

  const candidates = [
    `IconDesc_${base}.png`,
    `IconDesc_${base}s.png`,
    `IconDesc_${stripLiquid}.png`,
    `IconDesc_${base}_Pipe.png`,
    `${base}_Pipe.png`,
    `${stripLiquid}.png`,
    `${base}.png`,
    ...(display ? [`IconDesc_${display}.png`, `IconDesc_${display}s.png`, `${display}.png`, `${display}_Pipe.png`] : [])
  ];
  for (const c of candidates) {
    const file = findFile(c);
    if (file) return iconUrl(file);
  }
  return null;
}
